# INSTALLING THE LIBRARIES

In [5]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

* READING THE DATASET (MOVIES & RATINGS)

In [6]:
m_df = pd.read_csv('../data/movies.csv')

In [7]:
r_df = pd.read_csv('../data/ratings.csv')

* ANALYSING

In [8]:
m_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62423 entries, 0 to 62422
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  62423 non-null  int64
 1   title    62423 non-null  str
 2   genres   62423 non-null  str
dtypes: int64(1), str(2)
memory usage: 3.7 MB

In [9]:
r_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000095 entries, 0 to 25000094
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 762.9 MB

* CHECKING FOR NULL VALUES

In [10]:
m_df.isna().sum()

movieId    0
title      0
genres     0
dtype: int64

In [11]:
r_df.isna().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

* MERGING THE DATASETS
* THEN PERFORMING EDA

In [12]:
movies_df = pd.merge(m_df,r_df, on = 'movieId', how = 'left')

In [13]:
movies_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25003471 entries, 0 to 25003470
Data columns (total 6 columns):
 #   Column     Dtype
---  ------     -----
 0   movieId    int64
 1   title      str
 2   genres     str
 3   userId     float64
 4   rating     float64
 5   timestamp  float64
dtypes: float64(3), int64(1), str(2)
memory usage: 2.2 GB

* DROPING USER_ID AND TIMESTAMP BECAUSE THEY ARE OF NO USE

In [14]:
movies_df.drop(['userId','timestamp'],axis = 1, inplace = True)

In [15]:
# checking for null values
movies_df.isna().sum()

movieId       0
title         0
genres        0
rating     3376
dtype: int64

In [16]:
movies_df[movies_df['rating'].isna()]

,movieId,title,genres,rating
19111690,25817,Break of Hearts (1935),Drama|Romance,NaN
19152834,26361,Baby Blue Marine (1976),Drama,NaN
20655616,52696,"Thousand and One Nights, A (1001 Nights) (1945)",Adventure,NaN
21033023,56513,Suicide Killers (2006),Documentary,NaN
21128123,58209,Alex in Wonder (Sex and a Girl) (2001),Comedy|Drama,NaN
...,...,...,...,...
25003224,208411,Eternal Blood (2002),Action|Horror|Thriller,NaN
25003225,208413,Big Business (1929),Comedy,NaN
25003226,208415,The Student of Prague (1926),Horror,NaN
25003290,208655,The Coldest Game (2019),(no genres listed),NaN
25003376,208804,Spell (2018),Comedy|Drama|Thriller,NaN

* MORE THAN 3000 ROWS HAVE NaN VALUES IN RATINGS I HAVE TWO OPTIONS HERE : 
1. I CAN DROP ALL THESE NULL VALUES ROWS

2. COVERT THIS DATAFRAME INTO CSV GIVE IT TO AN A.I. TO FILL IN THE NULL VALUES WITH CORRECT RATINGS(PREFERABLLY IMBD RATINGS)

* LET US FIRST DO SOME EDA THEN I WILL GO FOR OPTION 2

* checking the null value count

* COVERTING THE FILE WAS EASY BUT UPLOADING IT ON AI WAS NOT POSSIBLE BEACAUSE THE FILE SIZE WAS VERY LARGE SO INSTEAD I AM MAKING THE CHANGES IN THE MOVIES_CSV FILE

* INSTEAD I HAVE MADE MY OWN PERSONLISED DATASET

In [18]:
movie_df = pd.read_csv('../data/movies_updated.csv')

In [19]:
movie_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62423 entries, 0 to 62422
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   movieId      62423 non-null  int64
 1   title        62423 non-null  str
 2   year         62423 non-null  int64
 3   genres       62423 non-null  str
 4   imdb_rating  62423 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.3 MB

In [20]:
movie_df.isna().sum()

movieId        0
title          0
year           0
genres         0
imdb_rating    0
dtype: int64

In [21]:
movie_df.sample(10)

,movieId,title,year,genres,imdb_rating
22466,115027,Appointment in Tokyo,1945,Documentary|War,6.4
52042,184449,Addicted To Fame,2012,Comedy|Documentary,6.3
55552,192199,Takumi-kun Series: Details of Beauty,2010,Drama,6.6
13602,70465,Jerusalema (Gangster's Paradise: Jerusalema),2008,Action|Crime|Drama,6.0
27251,128693,Expecting a Miracle,2009,Drama,4.6
49477,178965,Redwood,2017,Horror|Thriller,7.6
35518,148012,Desert Legion,1953,(no genres listed),6.2
4380,4485,Casual Sex?,1988,Comedy,6.1
60291,202956,Heart,1987,(no genres listed),7.2
8021,8735,High School Confidential!,1958,Crime|Drama,7.5

* ONLY WANT MOVIES FROM THE 1980S ONWARD

In [22]:
movie_df = movie_df[movie_df['year'] >= 1980]

In [23]:
movie_df.info()

<class 'pandas.DataFrame'>
Index: 45417 entries, 0 to 62421
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   movieId      45417 non-null  int64
 1   title        45417 non-null  str
 2   year         45417 non-null  int64
 3   genres       45417 non-null  str
 4   imdb_rating  45417 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.5 MB

* SOME EDA NEED TO BE PERFORMED ON THE GENRE COLUMN

In [29]:
(movie_df['genres'] == '(no genres listed)').sum()

np.int64(3439)

* MORE THAN 3000 COLUMNS DO NOT HAVE GENRE LISTED

In [35]:
movie_df = movie_df[movie_df['genres'] != '(no genres listed)']

In [36]:
movie_df.info()

<class 'pandas.DataFrame'>
Index: 41978 entries, 0 to 62420
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   movieId      41978 non-null  int64
 1   title        41978 non-null  str
 2   year         41978 non-null  int64
 3   genres       41978 non-null  str
 4   imdb_rating  41978 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.2 MB

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Just replace '|' with space — TF-IDF handles the rest
movie_df['genres'] = movie_df['genres'].str.replace('|', ' ')

# Vectorize
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(movie_df['genres'])

# Similarity matrix
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [41]:
genre_mood = {
    'Action': 'Excitement', 'Adventure': 'Excitement',
    'Animation': 'Joy', 'Children': 'Joy',
    'Comedy': 'Happy', 'Romance': 'Romantic',
    'Drama': 'Emotional', 'Horror': 'Thrilled',
    'Thriller': 'Thrilled', 'Mystery': 'Curious',
    'Crime': 'Curious', 'Sci-Fi': 'Wonder',
    'Fantasy': 'Wonder', 'Documentary': 'Inspired',
    'War': 'Reflective', 'History': 'Reflective',
    'Musical': 'Cheerful', 'Music': 'Cheerful',
    'Western': 'Adventurous', 'Film-Noir': 'Melancholic',
    'IMAX': 'Wonder',
}

def assign_mood(genres_str):
    if pd.isnull(genres_str):
        return 'Neutral'
    for genre in genres_str.split(' '):  # already replaced | with space
        if genre in genre_mood:
            return genre_mood[genre]
    return 'Neutral'

movie_df['mood'] = movie_df['genres'].apply(assign_mood)
movie_df[['title', 'genres', 'mood']].sample(10)

,title,genres,mood
54784,My Generation,Documentary,Inspired
39862,Superstar: The Life and Times of Andy Warhol,Documentary,Inspired
57376,Inuyashiki,Action,Excitement
15724,Life As a Fatal Sexually Transmitted Disease (...,Drama,Emotional
12819,The Manson Family,Crime Drama Horror,Curious
7809,"Distant Voices, Still Lives",Drama,Emotional
2004,The Rocketeer,Action Adventure Sci-Fi,Excitement
43253,Satan Lives,Documentary,Inspired
37937,The Wrestlers,Action Drama,Excitement
24892,The Duke,Children,Joy

In [42]:
movie_df = movie_df.reset_index(drop=True)
movie_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41978 entries, 0 to 41977
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   movieId      41978 non-null  int64
 1   title        41978 non-null  str
 2   year         41978 non-null  int64
 3   genres       41978 non-null  str
 4   imdb_rating  41978 non-null  float64
 5   mood         41978 non-null  str
dtypes: float64(1), int64(2), str(3)
memory usage: 3.5 MB

In [46]:
def recommend_movie(mood, genre, year_from=1980, n = 5):
    filtered = movie_df[
        (movie_df['mood'] == mood) &
        (movie_df['genres'].str.contains(genre, case=False)) &
        (movie_df['year'] >= year_from)
    ]
    return filtered.sort_values('imdb_rating', ascending=False)\
                   [['title', 'year', 'genres', 'imdb_rating', 'mood']]\
                   .head(n)

# Test it
recommend_movie('Excitement', 'Action')

,title,year,genres,imdb_rating,mood
41133,The Uninvited,2003,Action Horror Thriller,9.9,Excitement
34621,Stormageddon,2015,Action Drama Sci-Fi Thriller,9.9,Excitement
30813,Altitude,2017,Action Thriller,9.9,Excitement
36202,Occupation,2018,Action Sci-Fi,9.9,Excitement
4164,Rapid Fire,1992,Action,9.9,Excitement

In [47]:
movie_df.to_csv('../data/movies_final.csv', index=False)
print('Saved! Shape:', movie_df.shape)
movie_df.head()

Saved! Shape: (41978, 6)

,movieId,title,year,genres,imdb_rating,mood
0,1,Toy Story,1995,Adventure Animation Children Comedy Fantasy,8.4,Excitement
1,2,Jumanji,1995,Adventure Children Fantasy,6.0,Excitement
2,3,Grumpier Old Men,1995,Comedy Romance,8.6,Happy
3,4,Waiting to Exhale,1995,Comedy Drama Romance,6.6,Happy
4,5,Father of the Bride Part II,1995,Comedy,7.0,Happy

In [48]:
movie_df

,movieId,title,year,genres,imdb_rating,mood
0,1,Toy Story,1995,Adventure Animation Children Comedy Fantasy,8.4,Excitement
1,2,Jumanji,1995,Adventure Children Fantasy,6.0,Excitement
2,3,Grumpier Old Men,1995,Comedy Romance,8.6,Happy
3,4,Waiting to Exhale,1995,Comedy Drama Romance,6.6,Happy
4,5,Father of the Bride Part II,1995,Comedy,7.0,Happy
...,...,...,...,...,...,...
41973,209153,Happy Flight,2008,Comedy Drama,6.9,Happy
41974,209155,Santosh Subramaniam,2008,Action Comedy Romance,6.9,Excitement
41975,209157,We,2018,Drama,6.5,Emotional
41976,209159,Window of the Soul,2001,Documentary,8.9,Inspired
41977,209163,Bad Poems,2018,Comedy Drama,5.1,Happy